export const LOGINSUCCESS ="LOGINSUCCESS";
export const LOGINREQUEST ="LOGINREQUEST";
export const LOGINREJECTED ="LOGINREJECTED";

export const REGISTERSUCCESS ="REGISTERSUCCESS";
export const REGISTERREQUEST ="REGISTERREQUEST";
export const REGISTERREJECTED ="REGISTERREJECTED";

export const LOGOUT="LOGOUT";

export const VISITORSUCCESS ="VISITORSUCCESS";
export const VISITORREQUEST ="VISITORREQUEST";
export const VISITORREJECTED ="VISITORREJECTED";


export const ALLREGISTERSUCCESS ="ALLREGISTERSUCCESS";
export const ALLREGISTERREQUEST ="ALLREGISTERREQUEST";
export const ALLREGISTERREJECTED ="ALLREGISTERREJECTED";
